name: CI

on:
  push:
    branches: [main]

jobs:
  integrationTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install 
      - run: npm start &
      - run: npx newman run test/antsilgorIntegration.json
      - run: npx newman run test/integrationjuanchi.json
      - run: npx newman run test/integrationCarranza.json
      - run: node test/e2eCarranza.js


      